#!/bin/bash

echo "=== 修复完成 ==="
echo ""
echo "已将操作列从 TableAction 改为 CellOperation（与其他页面一致）"
echo ""
echo "修改的文件："
echo "  ✓ web/apps/web-antd/src/views/release/pipelineTemplate/data.ts"
echo "  ✓ web/apps/web-antd/src/views/release/pipelineTemplate/index.vue"
echo ""
echo "现在请执行："
echo ""
echo "1. 停止前端服务（Ctrl+C）"
echo ""
echo "2. 清除缓存并重启："
echo "   cd web"
echo "   rm -rf node_modules/.vite"
echo "   npm run dev:antd"
echo ""
echo "3. 刷新浏览器（Ctrl+Shift+R）"
echo ""
echo "应该能看到的按钮："
echo "  - 编辑"
echo "  - 版本管理"
echo "  - 复制 ← 新增"
echo "  - 导出 ← 新增"
echo "  - 删除"
