#!/bin/bash

echo "=== Jenkinsfile 编辑功能已添加 ==="
echo ""
echo "✅ 已添加功能："
echo "  1. 编辑版本内容 - 在版本管理中点击'编辑内容'"
echo "  2. 查看版本内容 - 在版本管理中点击'查看内容'"
echo "  3. 导出包含完整 Jenkinsfile 内容"
echo "  4. 导入包含完整 Jenkinsfile 内容"
echo ""
echo "📝 修改的文件："
echo "  ✓ versions.vue - 添加编辑内容功能"
echo "  ✓ pipelineTemplate.ts - 添加 updateVersionContent API"
echo ""
echo "🚀 现在请执行："
echo "  cd web"
echo "  rm -rf node_modules/.vite"
echo "  npm run dev:antd"
echo ""
echo "🧪 测试步骤："
echo "  1. 进入流水线模版列表"
echo "  2. 点击某个模版的'版本管理'"
echo "  3. 看到操作列有5个按钮："
echo "     - 设为最新"
echo "     - 编辑内容 ← 新增"
echo "     - 自动迭代"
echo "     - 编辑阶段"
echo "     - 查看内容"
echo "  4. 点击'编辑内容'，修改 Jenkinsfile"
echo "  5. 保存后点击'查看内容'验证"
echo "  6. 点击模版列表的'导出'，检查 JSON 中的 content 字段"
