#!/bin/bash

echo "=== 流水线模版功能测试指南 ==="
echo ""
echo "📋 完整功能清单已保存到: docs/Pipeline_Template_Checklist.md"
echo ""
echo "🧪 快速测试步骤："
echo ""
echo "1️⃣  创建模版"
echo "   - 点击'创建模板'按钮"
echo "   - 填写：名称=Test Java CI, 编码=test-java-ci"
echo "   - 选择：类型=CI, 语言=Java"
echo "   - 查看默认 Jenkinsfile 内容"
echo "   - 点击确定"
echo "   ✓ 验证：列表中出现新模版"
echo ""
echo "2️⃣  版本管理"
echo "   - 点击新模版的'版本管理'"
echo "   - 查看版本列表（应该有 1.0.0）"
echo "   - 点击'创建新版本'"
echo "   - 输入版本号 1.1.0"
echo "   - 点击创建"
echo "   ✓ 验证：版本列表中出现 1.1.0"
echo ""
echo "3️⃣  编辑内容"
echo "   - 点击版本 1.1.0 的'编辑内容'"
echo "   - 修改 Jenkinsfile（如添加注释）"
echo "   - 点击确定"
echo "   - 点击'查看内容'验证"
echo "   ✓ 验证：内容已更新"
echo ""
echo "4️⃣  自动迭代"
echo "   - 点击版本 1.1.0 的'自动迭代'"
echo "   - 确认对话框"
echo "   ✓ 验证：生成版本 1.1.1"
echo ""
echo "5️⃣  复制模版"
echo "   - 返回模版列表"
echo "   - 点击'复制'按钮"
echo "   ✓ 验证：生成 test-java-ci_copy 模版"
echo ""
echo "6️⃣  导出导入"
echo "   - 点击'导出'按钮"
echo "   - 打开 JSON 文件，检查 content 字段"
echo "   - 修改 JSON 中的 code 为 test-java-ci-imported"
echo "   - 点击'导入模板'，选择 JSON 文件"
echo "   ✓ 验证：导入成功"
echo ""
echo "7️⃣  编辑阶段"
echo "   - 进入版本管理"
echo "   - 点击'编辑阶段'"
echo "   - 选择 Build 阶段"
echo "   - 修改脚本"
echo "   - 点击确定"
echo "   ✓ 验证：阶段脚本已更新"
echo ""
echo "8️⃣  搜索筛选"
echo "   - 选择类型=CI"
echo "   - 输入名称搜索"
echo "   ✓ 验证：显示匹配结果"
echo ""
echo "9️⃣  删除模版"
echo "   - 点击测试模版的'删除'"
echo "   - 确认对话框"
echo "   ✓ 验证：模版已删除"
echo ""
echo "📊 功能统计："
echo "   ✅ 基础功能：创建、编辑、删除"
echo "   ✅ 版本管理：创建、编辑、查看、迭代"
echo "   ✅ 高级功能：复制、导出、导入"
echo "   ✅ 内容编辑：编辑内容、编辑阶段"
echo "   ✅ 辅助功能：搜索、筛选、排序"
echo ""
echo "📝 详细检查清单请查看："
echo "   docs/Pipeline_Template_Checklist.md"
