# Generated by Django 5.2.1 on 2026-02-28 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="应用名称")),
                ("code", models.CharField(max_length=32, verbose_name="应用编码")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="应用描述"
                    ),
                ),
                (
                    "app_type",
                    models.CharField(
                        choices=[
                            ("java", "Java"),
                            ("nodejs", "Node.js"),
                            ("python", "Python"),
                            ("go", "Go"),
                            ("vue", "Vue"),
                            ("react", "React"),
                        ],
                        max_length=16,
                        verbose_name="应用类型",
                    ),
                ),
                (
                    "git_url",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Git仓库地址",
                    ),
                ),
                (
                    "gitlab_project_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="GitLab Project ID"
                    ),
                ),
                (
                    "jenkins_ci_job",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Jenkins CI任务",
                    ),
                ),
                (
                    "jenkins_cd_job",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Jenkins CD任务",
                    ),
                ),
                (
                    "harbor_project",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Harbor项目"
                    ),
                ),
                (
                    "build_branch",
                    models.CharField(
                        default="main", max_length=64, verbose_name="构建分支"
                    ),
                ),
                (
                    "dockerfile_path",
                    models.CharField(
                        default="./Dockerfile",
                        max_length=128,
                        verbose_name="Dockerfile路径",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "禁用"), (1, "启用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "发布应用",
                "verbose_name_plural": "发布应用",
                "db_table": "release_application",
                "ordering": ["-sort", "-create_time"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="模块名称")),
                ("code", models.CharField(max_length=32, verbose_name="模块编码")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="模块描述"
                    ),
                ),
                (
                    "gitlab_subgroup_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="GitLab Subgroup ID"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "禁用"), (1, "启用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "发布模块",
                "verbose_name_plural": "发布模块",
                "db_table": "release_module",
                "ordering": ["-sort", "-create_time"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="项目名称")),
                (
                    "code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="项目编码"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="项目描述"
                    ),
                ),
                (
                    "gitlab_group_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="GitLab Group ID"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "禁用"), (1, "启用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "发布项目",
                "verbose_name_plural": "发布项目",
                "db_table": "release_project",
                "ordering": ["-sort", "-create_time"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="模板名称")),
                (
                    "code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="模板编码"
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("jenkinsfile", "Jenkinsfile"),
                            ("dockerfile", "Dockerfile"),
                            ("docker-compose", "Docker Compose"),
                        ],
                        max_length=16,
                        verbose_name="模板类型",
                    ),
                ),
                (
                    "app_type",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        verbose_name="适用应用类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="模板内容")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="模板描述"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "禁用"), (1, "启用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "发布模板",
                "verbose_name_plural": "发布模板",
                "db_table": "release_template",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ConfigPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                ("version", models.CharField(max_length=32, verbose_name="配置包版本")),
                (
                    "file_path",
                    models.CharField(max_length=256, verbose_name="文件路径"),
                ),
                ("file_size", models.BigIntegerField(verbose_name="文件大小(字节)")),
                (
                    "checksum",
                    models.CharField(max_length=64, verbose_name="文件校验和"),
                ),
                (
                    "sync_status",
                    models.IntegerField(
                        choices=[
                            (0, "待同步"),
                            (1, "同步中"),
                            (2, "已同步"),
                            (3, "同步失败"),
                        ],
                        default=0,
                        verbose_name="同步状态",
                    ),
                ),
                (
                    "sync_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="同步时间"
                    ),
                ),
                (
                    "sync_message",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="同步消息"
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_packages",
                        to="release.application",
                        verbose_name="关联应用",
                    ),
                ),
            ],
            options={
                "verbose_name": "配置包",
                "verbose_name_plural": "配置包",
                "db_table": "release_config_package",
                "ordering": ["-create_time"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="release.module",
                verbose_name="所属模块",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="release.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="release.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("harbor", "Harbor"),
                            ("jenkins", "Jenkins"),
                            ("ansible", "Ansible"),
                        ],
                        max_length=16,
                        verbose_name="同步类型",
                    ),
                ),
                (
                    "resource_name",
                    models.CharField(max_length=128, verbose_name="资源名称"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                        ],
                        max_length=16,
                        verbose_name="操作",
                    ),
                ),
                ("status", models.IntegerField(verbose_name="状态: 0-失败, 1-成功")),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="日志消息"
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="release.application",
                        verbose_name="应用",
                    ),
                ),
                (
                    "config_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="release.configpackage",
                        verbose_name="配置包",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="release.module",
                        verbose_name="模块",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="release.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "同步日志",
                "verbose_name_plural": "同步日志",
                "db_table": "release_sync_log",
                "ordering": ["-create_time"],
            },
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("project", "code"), name="uk_project_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("module", "code"), name="uk_module_code"
            ),
        ),
    ]
