# Generated by Django 5.2.1 on 2026-03-01 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvironmentStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="策略名称")),
                (
                    "code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="策略编码"
                    ),
                ),
                ("environment", models.CharField(max_length=32, verbose_name="环境")),
                (
                    "pipeline_mode",
                    models.CharField(
                        choices=[
                            ("integrated", "CI/CD 合并"),
                            ("separated", "CI/CD 分离"),
                        ],
                        max_length=32,
                        verbose_name="流水线模式",
                    ),
                ),
                (
                    "ci_jenkins",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="CI Jenkins 标识",
                    ),
                ),
                (
                    "cd_jenkins",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="CD Jenkins 标识",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(default=False, verbose_name="需要审批"),
                ),
                (
                    "auto_deploy",
                    models.BooleanField(default=False, verbose_name="自动部署"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="默认策略"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "禁用"), (1, "启用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "环境策略",
                "verbose_name_plural": "环境策略",
                "db_table": "release_environment_strategy",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="PipelineTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="模板名称")),
                (
                    "code",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="模板编码"
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[("ci", "CI 模板"), ("cd", "CD 模板")],
                        max_length=20,
                        verbose_name="模板类型",
                    ),
                ),
                ("language", models.CharField(max_length=32, verbose_name="编程语言")),
                (
                    "language_version",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="语言版本"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "framework",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="框架"
                    ),
                ),
                (
                    "is_official",
                    models.BooleanField(default=False, verbose_name="官方模板"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "禁用"), (1, "启用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "流水线模板",
                "verbose_name_plural": "流水线模板",
                "db_table": "release_pipeline_template",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="CDConfigExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                ("environment", models.CharField(max_length=32, verbose_name="环境")),
                ("config_version", models.IntegerField(verbose_name="配置版本")),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("jenkinsfile", "Jenkinsfile"),
                            ("json", "JSON 配置"),
                            ("yaml", "YAML 配置"),
                            ("zip", "压缩包"),
                        ],
                        max_length=20,
                        verbose_name="导出格式",
                    ),
                ),
                ("content", models.TextField(verbose_name="导出内容")),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="文件路径"
                    ),
                ),
                ("exported_by", models.CharField(max_length=64, verbose_name="导出人")),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="下载次数"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cd_exports",
                        to="release.application",
                        verbose_name="所属应用",
                    ),
                ),
            ],
            options={
                "verbose_name": "CD配置导出",
                "verbose_name_plural": "CD配置导出",
                "db_table": "release_cd_config_export",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="PipelineTemplateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                ("version", models.CharField(max_length=32, verbose_name="版本号")),
                ("content", models.TextField(verbose_name="模板内容 (Jenkinsfile)")),
                (
                    "variables",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="模板变量定义"
                    ),
                ),
                (
                    "stages",
                    models.JSONField(blank=True, default=list, verbose_name="阶段定义"),
                ),
                (
                    "change_log",
                    models.TextField(blank=True, null=True, verbose_name="变更日志"),
                ),
                (
                    "is_latest",
                    models.BooleanField(default=False, verbose_name="是否最新版本"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "禁用"), (1, "启用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="release.pipelinetemplate",
                        verbose_name="所属模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "模板版本",
                "verbose_name_plural": "模板版本",
                "db_table": "release_pipeline_template_version",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationPipelineConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                (
                    "config_type",
                    models.CharField(
                        choices=[("ci", "CI 配置"), ("cd", "CD 配置")],
                        max_length=20,
                        verbose_name="配置类型",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("dev", "开发环境"),
                            ("test", "测试环境"),
                            ("staging", "准生产环境"),
                            ("production", "生产环境"),
                        ],
                        max_length=32,
                        verbose_name="环境",
                    ),
                ),
                (
                    "custom_content",
                    models.TextField(blank=True, null=True, verbose_name="自定义内容"),
                ),
                (
                    "variables",
                    models.JSONField(blank=True, default=dict, verbose_name="变量值"),
                ),
                (
                    "stages_config",
                    models.JSONField(blank=True, default=list, verbose_name="阶段配置"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "current_version",
                    models.IntegerField(default=0, verbose_name="当前版本号"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_configs",
                        to="release.application",
                        verbose_name="所属应用",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configs",
                        to="release.pipelinetemplate",
                        verbose_name="关联模板",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configs",
                        to="release.pipelinetemplateversion",
                        verbose_name="模板版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "应用流水线配置",
                "verbose_name_plural": "应用流水线配置",
                "db_table": "release_application_pipeline_config",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationPipelineVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                ("version", models.IntegerField(verbose_name="版本号")),
                ("content", models.TextField(verbose_name="生成的 Jenkinsfile")),
                (
                    "variables_snapshot",
                    models.JSONField(blank=True, default=dict, verbose_name="变量快照"),
                ),
                (
                    "stages_snapshot",
                    models.JSONField(blank=True, default=list, verbose_name="阶段快照"),
                ),
                (
                    "generated_by",
                    models.CharField(max_length=64, verbose_name="生成人"),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="release.applicationpipelineconfig",
                        verbose_name="所属配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "应用配置版本",
                "verbose_name_plural": "应用配置版本",
                "db_table": "release_application_pipeline_version",
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("config", "version"), name="uk_config_version"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pipelinetemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version"), name="uk_template_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationpipelineconfig",
            constraint=models.UniqueConstraint(
                fields=("application", "config_type", "environment"),
                name="uk_app_config_type_env",
            ),
        ),
    ]
