# Generated by Django 5.2.1 on 2026-03-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0004_add_application_cicd_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinetemplateversion",
            name="stages_content",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="阶段脚本内容"
            ),
        ),
    ]
