# Generated by Django 5.2.1 on 2026-03-01 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0005_add_stages_content_and_version_methods"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="规则名称")),
                (
                    "code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="规则编码"
                    ),
                ),
                (
                    "environment",
                    models.CharField(max_length=32, verbose_name="适用环境"),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("single", "单人审批"),
                            ("any", "任意一人审批"),
                            ("all", "全部审批"),
                            ("sequential", "顺序审批"),
                        ],
                        max_length=32,
                        verbose_name="规则类型",
                    ),
                ),
                (
                    "approvers",
                    models.JSONField(default=list, verbose_name="审批人列表"),
                ),
                (
                    "min_approvers",
                    models.IntegerField(default=1, verbose_name="最少审批人数"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "禁用"), (1, "启用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "审批规则",
                "verbose_name_plural": "审批规则",
                "db_table": "release_approval_rule",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ReleaseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                ("branch", models.CharField(max_length=128, verbose_name="代码分支")),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("dev", "开发环境"),
                            ("test", "测试环境"),
                            ("staging", "准生产环境"),
                            ("production", "生产环境"),
                        ],
                        max_length=32,
                        verbose_name="目标环境",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="发布版本"
                    ),
                ),
                (
                    "require_approval",
                    models.BooleanField(default=False, verbose_name="需要审批"),
                ),
                (
                    "approval_type",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="审批类型"
                    ),
                ),
                (
                    "approvers",
                    models.JSONField(
                        blank=True, default=list, verbose_name="审批人列表"
                    ),
                ),
                (
                    "approval_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "approval_user",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="审批人"
                    ),
                ),
                (
                    "approval_comment",
                    models.TextField(blank=True, null=True, verbose_name="审批意见"),
                ),
                (
                    "jenkins_job_name",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Jenkins Job 名称",
                    ),
                ),
                (
                    "jenkins_build_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Jenkins 构建号"
                    ),
                ),
                (
                    "jenkins_build_url",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Jenkins 构建地址",
                    ),
                ),
                (
                    "jenkins_build_status",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Jenkins 构建状态",
                    ),
                ),
                (
                    "jenkins_build_duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="构建耗时(毫秒)"
                    ),
                ),
                (
                    "docker_image",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Docker 镜像",
                    ),
                ),
                (
                    "artifact_url",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="构建产物地址",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发布"),
                            ("approval_pending", "待审批"),
                            ("approved", "已审批"),
                            ("rejected", "已拒绝"),
                            ("building", "构建中"),
                            ("build_success", "构建成功"),
                            ("build_failed", "构建失败"),
                            ("deploying", "部署中"),
                            ("deployed", "已部署"),
                            ("rollback", "已回滚"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="发布状态",
                    ),
                ),
                (
                    "status_message",
                    models.TextField(blank=True, null=True, verbose_name="状态消息"),
                ),
                ("released_by", models.CharField(max_length=64, verbose_name="发布人")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="release.application",
                        verbose_name="所属应用",
                    ),
                ),
            ],
            options={
                "verbose_name": "发布记录",
                "verbose_name_plural": "发布记录",
                "db_table": "release_record",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ReleaseBuildLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                ("log_content", models.TextField(verbose_name="日志内容")),
                (
                    "log_type",
                    models.CharField(
                        default="console", max_length=32, verbose_name="日志类型"
                    ),
                ),
                (
                    "stage_name",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="阶段名称"
                    ),
                ),
                (
                    "stage_status",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="阶段状态"
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="build_logs",
                        to="release.releaserecord",
                        verbose_name="关联发布记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "构建日志",
                "verbose_name_plural": "构建日志",
                "db_table": "release_build_log",
                "ordering": ["create_time"],
            },
        ),
    ]
