# Generated by Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0006_add_release_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='gitlab_sync_message',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='GitLab 同步消息'),
        ),
        migrations.AddField(
            model_name='application',
            name='gitlab_sync_status',
            field=models.IntegerField(choices=[(0, '待同步'), (1, '同步中'), (2, '已同步'), (3, '同步失败')], default=0, verbose_name='GitLab 同步状态'),
        ),
        migrations.AddField(
            model_name='application',
            name='gitlab_sync_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='GitLab 最后同步时间'),
        ),
        migrations.AddField(
            model_name='application',
            name='harbor_sync_message',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Harbor 同步消息'),
        ),
        migrations.AddField(
            model_name='application',
            name='harbor_sync_status',
            field=models.IntegerField(choices=[(0, '待同步'), (1, '同步中'), (2, '已同步'), (3, '同步失败')], default=0, verbose_name='Harbor 同步状态'),
        ),
        migrations.AddField(
            model_name='application',
            name='harbor_sync_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Harbor 最后同步时间'),
        ),
    ]
