# Generated by Django
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0007_add_gitlab_harbor_sync_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='仓库名称')),
                ('code', models.CharField(max_length=32, verbose_name='仓库编码')),
                ('repository_type', models.CharField(choices=[('gitlab', 'GitLab'), ('github', 'GitHub'), ('gitee', 'Gitee')], default='gitlab', max_length=16, verbose_name='仓库类型')),
                ('gitlab_project_id', models.IntegerField(blank=True, null=True, verbose_name='GitLab Project ID')),
                ('git_url', models.CharField(max_length=256, verbose_name='Git 仓库地址')),
                ('code_subpath', models.CharField(blank=True, help_text='仓库内的子目录，用于多模块项目构建', max_length=128, null=True, verbose_name='代码子目录')),
                ('build_command', models.CharField(blank=True, help_text='如：mvn package -pl {subpath} -am', max_length=256, null=True, verbose_name='构建命令')),
                ('package_name', models.CharField(blank=True, help_text='如：xxx.jar, xxx.tar.gz', max_length=128, null=True, verbose_name='打包产物名称')),
                ('default_branch', models.CharField(default='main', max_length=64, verbose_name='默认分支')),
                ('status', models.SmallIntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='状态')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='仓库描述')),
                ('creator', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=64, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_repositories', to='release.module', verbose_name='所属模块')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_repositories', to='release.project', verbose_name='所属项目')),
            ],
            options={
                'db_table': 'release_code_repository',
                'verbose_name': '代码仓库',
                'verbose_name_plural': '代码仓库',
                'ordering': ['-create_time'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.AddField(
            model_name='application',
            name='code_repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='release.coderepository', verbose_name='代码仓库'),
        ),
        migrations.AddField(
            model_name='application',
            name='code_subpath',
            field=models.CharField(blank=True, help_text='仓库内的子目录，用于多模块项目构建', max_length=128, null=True, verbose_name='代码子目录'),
        ),
    ]
