# Generated by Django 5.2.1 on 2026-03-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0008_add_code_repository'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coderepository',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='coderepository',
            name='git_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Git 仓库地址'),
        ),
        migrations.AlterField(
            model_name='coderepository',
            name='status',
            field=models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='状态'),
        ),
        migrations.AddConstraint(
            model_name='coderepository',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='uk_repo_project_code'),
        ),
        migrations.AddConstraint(
            model_name='coderepository',
            constraint=models.UniqueConstraint(condition=models.Q(('gitlab_project_id__isnull', False)), fields=('gitlab_project_id',), name='uk_repo_gitlab_id'),
        ),
    ]
