# Generated by Django 5.2.1 on 2026-03-10 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0009_alter_coderepository_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coderepository',
            name='build_command',
        ),
        migrations.RemoveField(
            model_name='coderepository',
            name='code_subpath',
        ),
        migrations.RemoveField(
            model_name='coderepository',
            name='package_name',
        ),
    ]
