# Generated by Django 5.2.1 on 2026-03-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0010_remove_coderepository_build_command_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="gitlab_sync_message",
            field=models.TextField(
                blank=True, null=True, verbose_name="GitLab 同步消息"
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="gitlab_sync_status",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="GitLab 同步状态"
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="gitlab_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="GitLab 最后同步时间"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="gitlab_sync_message",
            field=models.TextField(
                blank=True, null=True, verbose_name="GitLab 同步消息"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="gitlab_sync_status",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="GitLab 同步状态"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="gitlab_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="GitLab 最后同步时间"
            ),
        ),
    ]
