# Generated by Django 5.2.1 on 2026-03-14 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0011_module_gitlab_sync_message_module_gitlab_sync_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderepository',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_repositories', to='release.project', verbose_name='所属项目'),
        ),
    ]
