# Generated by Django 5.2.1 on 2026-03-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0012_alter_coderepository_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="build_command",
            field=models.CharField(
                blank=True,
                help_text="如：mvn clean package 或 npm run build",
                max_length=256,
                null=True,
                verbose_name="编译命令",
            ),
        ),
    ]
