# Generated by Django 5.2.1 on 2026-03-14 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0013_application_build_command"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="release.module",
                verbose_name="所属模块",
            ),
        ),
    ]
