# Generated by Django 5.2.1 on 2026-03-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0014_alter_application_module"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="application",
            name="uk_module_code",
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                condition=models.Q(("module__isnull", False)),
                fields=("project", "module", "code"),
                name="uk_project_module_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                condition=models.Q(("module__isnull", True)),
                fields=("project", "code"),
                name="uk_project_code_when_no_module",
            ),
        ),
    ]
