# Generated by Django 5.2.1 on 2026-07-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0015_remove_application_uk_module_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="releaserecord",
            name="conversation_id",
            field=models.BigIntegerField(
                blank=True,
                db_comment="关联 ai_chat_conversation 的 id",
                null=True,
                verbose_name="关联 AI 对话编号",
            ),
        ),
    ]
