# Generated by opencode: refactor pipeline system to remove CI/CD separation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0016_add_conversation_id"),
    ]

    operations = [
        # Remove config_type unique constraint first (it references config_type)
        migrations.RemoveConstraint(
            model_name="applicationpipelineconfig",
            name="uk_app_config_type_env",
        ),
        # Remove config_type from ApplicationPipelineConfig
        migrations.RemoveField(
            model_name="applicationpipelineconfig",
            name="config_type",
        ),
        # Add new unique constraint on (application, environment)
        migrations.AddConstraint(
            model_name="applicationpipelineconfig",
            constraint=models.UniqueConstraint(
                fields=("application", "environment"),
                name="uk_app_env",
            ),
        ),
        # Remove CI/CD fields from Application
        migrations.RemoveField(
            model_name="application",
            name="ci_template",
        ),
        migrations.RemoveField(
            model_name="application",
            name="cd_template",
        ),
        migrations.RemoveField(
            model_name="application",
            name="ci_variables",
        ),
        migrations.RemoveField(
            model_name="application",
            name="cd_variables",
        ),
        migrations.RemoveField(
            model_name="application",
            name="jenkins_ci_job",
        ),
        migrations.RemoveField(
            model_name="application",
            name="jenkins_cd_job",
        ),
        # Remove template_type from PipelineTemplate
        migrations.RemoveField(
            model_name="pipelinetemplate",
            name="template_type",
        ),
        # Remove CI/CD related fields from EnvironmentStrategy
        migrations.RemoveField(
            model_name="environmentstrategy",
            name="pipeline_mode",
        ),
        migrations.RemoveField(
            model_name="environmentstrategy",
            name="ci_jenkins",
        ),
        migrations.RemoveField(
            model_name="environmentstrategy",
            name="cd_jenkins",
        ),
        # Delete old Template model
        migrations.DeleteModel(
            name="Template",
        ),
    ]
