# Generated by Django 5.2.1 on 2026-07-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0017_remove_cicd_separation"),
    ]

    operations = [
        migrations.AddField(
            model_name="coderepository",
            name="git_http_url",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Git HTTP 地址"
            ),
        ),
        migrations.AlterField(
            model_name="coderepository",
            name="git_url",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Git SSH 地址"
            ),
        ),
    ]
