# Generated by opencode: remove CDConfigExport model

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0018_add_git_http_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CDConfigExport",
        ),
    ]
