# Generated by Django 5.2.1 on 2026-07-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0019_remove_cd_config_export"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationpipelineconfig",
            name="config_dirty",
            field=models.BooleanField(default=False, verbose_name="配置已变更待同步"),
        ),
        migrations.AlterField(
            model_name="application",
            name="jenkins_sync_status",
            field=models.IntegerField(
                choices=[
                    (0, "待同步"),
                    (1, "同步中"),
                    (2, "已同步"),
                    (3, "同步失败"),
                    (4, "待重新同步"),
                    (5, "未配置"),
                ],
                default=0,
                verbose_name="Jenkins 同步状态",
            ),
        ),
    ]
