# Generated by Django 5.2.1 on 2026-08-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0020_applicationpipelineconfig_config_dirty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coderepository",
            name="code",
            field=models.CharField(max_length=256, verbose_name="仓库编码"),
        ),
    ]
