# Generated by Django 5.2.1 on 2026-08-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0021_alter_coderepository_code_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coderepository",
            name="name",
            field=models.CharField(max_length=256, verbose_name="仓库名称"),
        ),
    ]
