# Generated by Django 5.2.1 on 2026-08-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0022_alter_coderepository_name_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="code",
            field=models.CharField(max_length=128, verbose_name="应用编码"),
        ),
        migrations.AlterField(
            model_name="application",
            name="name",
            field=models.CharField(max_length=128, verbose_name="应用名称"),
        ),
    ]
