# Generated by opencode: remove EnvironmentStrategy model

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0025_remove_approvalrule_is_default"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EnvironmentStrategy",
        ),
    ]
