# Generated by Django 5.2.1 on 2026-07-29 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0005_cityarea"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="data_scope",
            field=models.CharField(
                choices=[
                    ("all", "全部数据"),
                    ("custom", "自定义数据（按中央关联表分配）"),
                    ("dept", "本部门数据"),
                    ("self", "仅本人数据"),
                ],
                default="self",
                max_length=20,
                verbose_name="数据权限范围",
            ),
        ),
        migrations.CreateModel(
            name="DataPermissionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="资源类型"
                    ),
                ),
                (
                    "scope_id",
                    models.BigIntegerField(db_index=True, verbose_name="资源ID"),
                ),
                (
                    "level",
                    models.CharField(
                        default="member", max_length=20, verbose_name="权限级别"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_permission_rules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据权限规则",
                "verbose_name_plural": "数据权限规则",
                "db_table": "system_data_permission_rule",
                "unique_together": {("scope_type", "scope_id", "user")},
            },
        ),
    ]
